language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
    - 7.4
    - 8.0

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

before_script:
  - mkdir -p coverage

script:
  - php vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
    email: false
